#!/res/bin/busybox sh
BB=/res/bin/busybox
INC=/data/PRIME-Kernel/bin/volt.inc

if [ ! -e $INC ]; then
  case $($BB basename $0) in
    cpuvolt)
      P=/sys/devices/system/cpu/cpufreq/mp-cpufreq/cpu_volt_table;;
    kfcvolt)
      P=/sys/devices/system/cpu/cpufreq/mp-cpufreq/kfc_volt_table;;
    gpuvolt)
      P=/sys/devices/14ac0000.mali/volt_table;;
    intvolt)
      P=/sys/class/devfreq/exynos5-devfreq-int/volt_table;;
    mifvolt)
      P=/sys/class/devfreq/exynos5-devfreq-mif/volt_table;;
    ispvolt)
      P=/sys/class/devfreq/exynos5-devfreq-isp/volt_table;;
  esac
  readValue() {
	while read FREQ UVOLT; do
      if [ $FREQ == $1 ]; then
          echo $UVOLT
          return
      fi
    done < $P
  }
  echo $(readValue $1)
else
  source $INC
fi
